### ISSUE TITLE
Update Netdata to latest version

### ISSUE THREAD

**Issue by rklos** [caprover/netdata-docker#2]
Hi, there is a chance to update Netdata? Currently used 1.18.0 version is 3 years old. Latest version has more features including a better system for storing statistics (not only in RAM, but also on disk).
@githubsaturn

**Comment by githubsaturn** [comment]
Future versions of Netdata have telemetry enabled by default. I haven't had time to investigate how to upgrade and safely disable telemetry. Feel free to take a look and open a PR.

**Comment by rklos** [comment]
Hi @githubsaturn, I made a PR with upgrade to latest version.
Please take a look when you have a moment.
